### ISSUE TITLE
Bootstrap should use local JS

### ISSUE THREAD

**Issue by AuroraBTH** [aurora-munge/databasteknik#35]
Bootstrap is currently using local CSS files but was unsure how to load the local JS files (as the CSS is loaded via `PageRender`). Files exists in vendor after `composer install`.

**Comment by AuroraBTH** [comment]
### Files used:
-- `jquery-3.2.1.slim.min.js` --
Located at: `vendor/twbs/bootstrap/assets/js/vendor/jquery-slim.min.js` (I think it's the correct file)
-- `popper.min.js` --
Located at `vendor/twbs/bootstrap/assets/js/vendor/popper.min.js`
-- `bootstrap.min.js` --
Located at `vendor/twbs/bootstrap/dist/js/bootstrap.min.js`

**Comment by MagnusGreiff** [comment]
Fixed in #37.
